"""empty message

Revision ID: 6e1766dbe8bf
Revises: f1963c054e7a
Create Date: 2023-12-18 13:26:16.861152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e1766dbe8bf'
down_revision = 'f1963c054e7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('intervention', schema=None) as batch_op:
        batch_op.alter_column('admin_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('redflag', schema=None) as batch_op:
        batch_op.alter_column('admin_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('redflag', schema=None) as batch_op:
        batch_op.alter_column('admin_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('intervention', schema=None) as batch_op:
        batch_op.alter_column('admin_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
